import turtle
turtle.Screen().bgcolor("white")
board=turtle.Turtle()
board.forward(100)
board.left(60)
board.forward(100)
board.left(60)
board.forward(100)
board.left(60)
board.forward(100)
board.left(60)
board.forward(100)
board.left(60)
board.forward(100)
board.left(60)
turtle.done()